### ISSUE TITLE
What will make a labeledSystem's length equals to zero?

### ISSUE THREAD

**Issue by wxy20010110** [deepmodeling/dpdata#117]
I used the command :
_sys = dpdata.LabeledSystem(ss, type_map = ['Co','Ni'])
Unfortunately, len(_sys)=0. What's wrong with it?

**Comment by wxy20010110** [comment]
[OUTCAR.zip](https://github.com/deepmodeling/dpdata/files/5353238/OUTCAR.zip)
and here is the OUTCAR

**Comment by njzjz** [comment]
Your calculation is not converged, so `dpdata` dropped it. This is the expected behavior.
