### ISSUE TITLE
VASP virial data processing

### ISSUE THREAD

**Issue by ssrokyz** [deepmodeling/dpdata#119]
Hello.

Considering the link below, virial.raw file should include virials in the unit of eV, not virial pressure in kBar.
[https://github.com/deepmodeling/deepmd-kit/issues/230](https://github.com/deepmodeling/deepmd-kit/issues/230)

Since the virial pressure of the VASP OURCAR file including is 'pressure' in unit kBar,
isn't it right to multiply the volume of the box to make 'virial.raw' file?

But I couldn't find any part multiplying volume.
Please let me know if I'm understanding wrong.

thx!
Sincerely, YJ Choi

**Comment by AnguseZhang** [comment]
Hi,
dpdata's behavior is correct. Virial (in eV) is obtained by multiplying the volume in 
https://github.com/deepmodeling/dpdata/blob/master/dpdata/system.py#L1176

**Comment by AnguseZhang** [comment]
Since the codes will be updated, above link may be deprecated. I left a link with tag version. 
The volume conversion is done at https://github.com/deepmodeling/dpdata/blob/59dfe7dd1cbc576a176430ca584a35f261fee1c4/dpdata/system.py#L1294
