### ISSUE TITLE
The cp2k module gives incorrect result

### ISSUE THREAD

**Issue by singlebook** [deepmodeling/dpdata#126]
The default unit for coordinate of cp2k output is angstrom, but dpdata considers it as bohr, and make a transformation. 
line 193~ 195 in dpdata/cp2k/output.py /
            coords_list.append([float(line_list[1])*AU_TO_ANG,
                float(line_list[2])*AU_TO_ANG,
                float(line_list[3])*AU_TO_ANG])

**Comment by robinzyb** [comment]
Yes, we checked the code, now submit a pull request

> The default unit for coordinate of cp2k output is angstrom, but dpdata considers it as bohr, and make a transformation.
> line 193~ 195 in dpdata/cp2k/output.py /
> coords_list.append([float(line_list[1])*AU_TO_ANG,
> float(line_list[2])*AU_TO_ANG,
> float(line_list[3])*AU_TO_ANG])

**Comment by felix5572** [comment]
@singlebook  
take a look? 
#127

**Comment by njzjz** [comment]
Close since it has been fixed by #127
