### ISSUE TITLE
Failed to read cp2k aimd files from restarted files

### ISSUE THREAD

**Issue by dmh1998dmh** [deepmodeling/dpdata#139]
When reading cp2k aimd outputs from restarted files, dpdata goes error with "AssertionError: (array([*******], dtype=float32), array([*******], dtype=float32), 'There may be errors in the file')"
Because with a start of cp2k aimd run, the initialized step (0th) was writen both in xyz and log files, but with a restart from former aimd runs, the initialized step was not written in xyz file.
dpdata failed to match the first energy in log and xyz file from a restarted aimd run.

**Comment by felix5572** [comment]
Could you please show the restart xyz and log file. 

And do you think how to deal with this situlation is better?

**Comment by dmh1998dmh** [comment]
[ch4.zip](https://github.com/deepmodeling/dpdata/files/6334750/ch4.zip)
As showing the restart log, cp2k run 6 steps including the initialized step(5th step), and it starts from 6th step in xyz file(only 5 steps).

I'm trying to solve this with skipping the first step in log file when a restart aimd output is detected.

**Comment by njzjz** [comment]
Fixed in #140
