### ISSUE TITLE
The dpdata is not supported with the vasp6.2.0 for make data set.

### ISSUE THREAD

**Issue by zcb-code** [deepmodeling/dpdata#146]
**Summary**
If I use dpdata to collect the data set form outcar calculated with vasp.6.2. I will get :
Traceback (most recent call last):
  File "outtdp.py", line 13, in <module>
    if len(ls)>0:
NameError: name 'ls' is not defined
===================================================================
the script  dp.py I used :

from dpdata import LabeledSystem,MultiSystems
from glob import glob
"""
process multi systems
"""
fs=glob('./OUTCAR')  # remeber to change here !!!
ms=MultiSystems()
for f in fs:
    try:
        ls=LabeledSystem(f)
    except:
        print(f)
    if len(ls)>0:
        ms.append(ls)

ms.to_deepmd_raw('deepmd')
ms.to_deepmd_npy('deepmd')
===================================================================
the appendix is the OUTCAR calculated in vasp5.4.4 and vasp6.2.0 edition. How to fix this?

[OUTCAR5.4.4.log](https://github.com/deepmodeling/dpdata/files/6383018/OUTCAR5.4.4.log)
[OUTCAR6.2.0.log](https://github.com/deepmodeling/dpdata/files/6383019/OUTCAR6.2.0.log)

**Comment by njzjz** [comment]
Close since #151 has been merged.
