### ISSUE TITLE
[BUG] Failure in Gaussian's parser

### ISSUE THREAD

**Issue by Zhang-pchao** [deepmodeling/dpdata#148]
After Gaussian has calculated all the cluster candidates, it terminates in step 8. 
run.log reports an error ValueError: could not convert string to float: '219.870882556-1030.493229556'.

If other documents are needed, I can provide them in time. 
[run.log](https://github.com/deepmodeling/dpdata/files/6424815/run.log)

**Comment by Zhang-pchao** [comment]
> @Zhang-pchao could you post the Gaussian log files that can be a test?

[output_pm6d3.log](https://github.com/deepmodeling/dpdata/files/6445059/output_pm6d3.log)

**Comment by Zhang-pchao** [comment]
> > @Zhang-pchao could you post the Gaussian log files that can be a test?
> 
> [output_pm6d3.log](https://github.com/deepmodeling/dpdata/files/6445059/output_pm6d3.log)

I found that if I change "fp_task_max" from 1000 to 600, it can run. Could this bug be due to too many cluster candidates selected?

**Comment by njzjz** [comment]
I don't find `219.870882556-1030.493229556` in output_pm6d3.log.

**Comment by njzjz** [comment]
> > @njzjz Would you please see this issue ?
> 
> I am studying [what ASE does](https://gitlab.com/ase/ase/-/blob/3.21.1/ase/io/gaussian.py#L256-262).

Oh, I found ASE also has this bug... Let me consider how to resolve it.

**Comment by amcadmus** [comment]
Fixed by #155, close
