### ISSUE TITLE
[Feature Request] Converting OUTCAR not fully successful when NWRITE is specified in INCAR

### ISSUE THREAD

**Issue by DingChangjie** [deepmodeling/dpdata#152]
**Summary**

When a user specified NWRITE in INCAR before they begins a vasp task, Vasp may not dump enough information into OUTCAR, i.e. some keywords are missing. Thus the converted type_map.raw will be empty. 

**Detailed Description**

In my case for instance. As a beginner, I manually specified NWRITE=1, which suppressed some vital information including keyword **TITEL** to be dumped into OUTCAR. This prevented dpdata from recognizing Elements(C, Zr and W) by keyword TITEL.
So finally I had to manually add rows like "TITEL  = PAW_PBE C 08Apr2002" as a workaround...
An excerption of my OUTCAR(a C-Zr-W system) is attached in the end. I suggest users be informed of this by an enhanced version of dpdata/dpdata's documentation.

**Further Information, Files, and Links**
... 
INCAR:
 POTCAR:    PAW_PBE C 08Apr2002                   
 POTCAR:   PAW_PBE Zr 08Apr2002                   
 POTCAR:    PAW_PBE W 08Apr2002                   
....
 POTCAR:    PAW_PBE C 08Apr2002 
    **<Missing lots of keywords from POTCAR, including the most important TITEL>**                 
  local pseudopotential read in
  partial core-charges read in
  partial kinetic energy density read in
  atomic valenz-charges read in
  non local Contribution for L=           0  read in
    real space projection operators read in
  non local Contribution for L=           0  read in
    real space projection operators read in
  non local Contribution for L=           1  read in
    real space projection operators read in
  non local Contribution for L=           1  read in
    real space projection operators read in
    PAW grid and wavefunctions read in
 
   number of l-projection  operators is LMAX  =           4
   number of lm-projection operators is LMMAX =           8
...

**Comment by AnguseZhang** [comment]
Hi Changjie,  thanks for reporting.  dpdata currently only supports for `NWRITE=2`. As you mentioned, if `NWRITE`,the atom type is missing, which is vital for dpdata. Even worse, someone tried `NWRITE=0`, and in an AIMD trajectory, only the firt and last coordinates and forces are recorded. He tried to use `dpdata` to extract information, and failed.

VASP's default value for NWRITE is 2. So now we do not intend to support other options, but we can give users warnings.   But you're welcomed to propose your suggestions about how to enhance this function.

![image](https://user-images.githubusercontent.com/38939321/117535840-3c32a880-b02a-11eb-8576-98e7537d269a.png)

Yuzhi

**Comment by DingChangjie** [comment]
Hi Yuzhi:
Thanks for your response in time! Though I'm still a beginner in DP, I'll try to study it deeper
