### ISSUE TITLE
Dpdata with DFTB+

### ISSUE THREAD

**Issue by zcb-code** [deepmodeling/dpdata#167]
Will DFTB+(https://dftbplus.org/about-dftb) be added to dpdata?

**Comment by bhourahine** [comment]
Is there a preferred way to connect to external codes? In [DFTB+](https://github.com/dftbplus) we generate machine readable tagged files (which we consider to be more robust than parsing the human readable data) but also off an API and [i-PI](http://ipi-code.org/) socket communication.

**Comment by njzjz** [comment]
I'm refactoring dpdata in #168 to add a plugin system. When it's ready, it will become much easier to add a format without changing the main program of dpdata, and it will be possible to add a format outside dpdata.

**Comment by zcb-code** [comment]
> I'm refactoring dpdata in #168 to add a plugin system. When it's ready, it will become much easier to add a format without changing the main program of dpdata, and it will be possible to add a format outside dpdata.

Thanks. I will try when it is ok.

**Comment by bhourahine** [comment]
It probably would make sense to look at a plugin for ASE or one of the other integrated frameworks, as this rapidly provides access to many different codes (including DFTB+).
