### ISSUE TITLE
Use `setuptools_scm` instead of `setuptools-git-version`

### ISSUE THREAD

**Issue by xhochy** [deepmodeling/dpdata#18]
I just saw in https://github.com/conda-forge/staged-recipes/pull/8786/files that your PyPI sdist doesn't contain the version number which makes redistribution a bit harder. You should get that fixed by using the more popular `setuptools_scm` for getting the version number from git. This also takes care that the sdist has the version number baked in correctly.

**Comment by amcadmus** [comment]
Use `setuptools_scm` since version 0.1.1
