### ISSUE TITLE
Problem reading multiple OUTCAR files

### ISSUE THREAD

**Issue by Miserablegit75** [deepmodeling/dpdata#185]
**Summary**
When reading multiple OUTCAR files having different numbers of frames, dpdata does not read all the files.

**Detailed Description**
I'm analyzing historical data and only OUTCAR files are available. When I try to read a group of seven OUTCAR files representing a single lengthy trajectory, only the first three files (each having the same number of frames) are read. The remaining OUTCAR files (having differing numbers of frames) appear to be ignored. Is there a fix for this in the current release or would it be possible to to generalize the current code to allow it to read multiple OUTCAR files each having a different number of frames? Thanks much. 

**Further Information, Files, and Links**
Here is a portion of the script I'm using:

from dpdata import LabeledSystem,MultiSystems
from glob import glob
#
fs=glob('../OUTCAR.swf0.*')
ms=MultiSystems()
for f in fs:
        try:
                ls=LabeledSystem(f,fmt = 'vasp/outcar')
        except:
                print(f)
        if len(ls)>0:
                ms.append(ls)
#
ms.to_deepmd_raw('deepmd')
ms.to_deepmd_npy('deepmd')

This script generates the following files & directories:
box.raw  coord.raw  energy.raw  force.raw  set.000  set.001  set.002  type_map.raw  type.raw  virial.raw

Apparently, only the first three OUTCAR files (each having the same number of frames) were read. The last four OUTCAR files (having different numbers of frames) were apparently not read. 

Each 'set' directory looks like this:
box.npy  coord.npy  energy.npy  force.npy  virial.npy

**Comment by njzjz** [comment]
This is an expected behavior. These sets are not divided by OUTCAR files. The number of frames in each set is decided by `set_size` argument (default is 5000).
https://github.com/deepmodeling/dpdata/blob/ea32d453d17600348e8cca69d7d07f40e54c6b84/dpdata/plugins/deepmd.py#L45-L46

**Comment by Miserablegit75** [comment]
Many thanks!
