### ISSUE TITLE
Error with new version of CP2K package

### ISSUE THREAD

**Issue by fmatusalem** [deepmodeling/dpdata#196]
Dear developers, 

I'm having problems to use dpdata to import files from new version of CP2K package. Is this an issue or something I'm missing? 

I made the calculation with the new CP2K version for the ~/dpdata/tests/cp2k/aimd directory and after that I got the problem. 

Best regards, 
Thank you
Filipe

**Comment by amcadmus** [comment]
@robinzyb could you plz take a look? Thanks!

**Comment by robinzyb** [comment]
Hi, I'm using cp2k 7.1 version now. Can you provide `input_file` , `output_file`. So that I can quickly spot the problem

**Comment by dmh1998dmh** [comment]
> Hi, I'm using cp2k 7.1 version now. Can you provide `input_file` , `output_file`. So that I can quickly spot the problem

[82aimd.zip](https://github.com/deepmodeling/dpdata/files/7743972/82aimd.zip)
Many things changed, including potential energies, cell information.

**Comment by robinzyb** [comment]
```python
import dpdata
cp2kmd_dir = "./82aimd/"
cp2kmd_output_name = "H2O-32.log"
dp = dpdata.LabeledSystem(cp2kmd_dir, cp2k_output_name=cp2kmd_output_name, fmt="cp2kdata/md")
print(dp)
```
```shell
ValueError: please provide cp2k output file with MEDIUM print level. Print Level Low doesn't provide necessary information for initialize the cp2kdata class.
```
The print level should be MEDIUM.
Now cp2kdata plug-in can support to 2023.1 version of cp2k. including both energy_force and md calculations.
https://github.com/link89/cp2kdata/tree/fix-2023-support
