### ISSUE TITLE
Failed to read cp2k aimd files -  energy difference between xyz and log 

### ISSUE THREAD

**Issue by TinacciL** [deepmodeling/dpdata#210]
Hello,
when reading cp2k aimd outputs ( ```dpdata.LabeledSystem('test_read_cp2k', fmt='cp2k/aimd_output')```) I found this error:
```
assert log_info_dict['energies']==xyz_info_dict['energies'], (log_info_dict['energies'][0], xyz_info_dict['energies'][0],'There may be errors in the file')
AssertionError: (-10087.061, -10087.062, 'There may be errors in the file')
```
I controlled the error and it seems a numeric error due to the conversion from a.u. to eV and/or the used of float with different mantissa since in the ```.xyz``` it is reported -370.6925172920 and  in the ```.log``` -370.692517291966794. 

I'm running dpdata 0.2.1 intalled with pip with python 3.9.7 and numpy 1.21.2.

Thanks, 
Lorenzo

**Comment by robinzyb** [comment]
Hi, sorry for late reply. I checked your log, found two 10,000 md trajectories in output and only 10,000 steps in xyz. After I deleted the first 10,000 steps in log, dpdata worked fine.  I guess what the trajectory in xyz matches is the second 10,000 steps in log file. So no bugs here, just the mismatch of log file and xyz.
