### ISSUE TITLE
Dpdata is not compatible with vasp6.3

### ISSUE THREAD

**Issue by WU2JING** [deepmodeling/dpdata#241]
**Summary**

When i try to use vasp6.3 to create training sets, these are some problems.

![image](https://user-images.githubusercontent.com/68996784/152949536-56af8e3a-da8d-4594-8bee-9658267f037a.png)

**Comment by wanghan-iapcm** [comment]
Please check  #239

**Comment by njzjz** [comment]
Fixed by #239 and #244.
