### ISSUE TITLE
The trouble encountered in extracting data from 'OUTCAR'

### ISSUE THREAD

**Issue by Superionichuan** [deepmodeling/dpdata#255]
I 've meet troubles in extracting data from OUTCAR (AIMD) using this script:
#script#
from dpdata import LabeledSystem,MultiSystems
from glob import glob
"""
process multi systems
"""
fs=glob('OUTCAR')  # remeber to change here !!!
ms=MultiSystems()
for f in fs:
    try:
        ls=LabeledSystem(f)
    except:
        print(f)
    if len(ls)>0:
        ms.append(ls)

ms.to_deepmd_raw('deepmd')
ms.to_deepmd_npy('deepmd',set_size=2000)
##
My OUTCAR contains three kinds of atoms and the errors are reported as follows:
#Error Report#
Traceback (most recent call last):
  File "script.py", line 13, in <module>
    if len(ls)>0:
NameError: name 'ls' is not defined
#
The above script does not report an error when dealing monatomic system.

**Comment by phyang9** [comment]
Hello shichuan, i'm a beginner of dpgen code, i encountered the same question when i run the init_bulk step to produce the initial data set of the deepd-kit by using dpdata code to convert the 'OUTCAR' to 'npy' files, have you fixed it and could you please share your way, any advices you provide will be appreciated.

**Comment by Superionichuan** [comment]
The problem has been sovled. Fix "NWRITE=2" when you conduct an AIMD simulation to get OUTCAR.
