### ISSUE TITLE
[BUG] issue with format 'qe/pw/scf'

### ISSUE THREAD

**Issue by zyliu06** [deepmodeling/dpdata#268]
**Summary**

The format 'qe/pw/scf' does not give correct atomic coordinate when the input 'ATOMIC_POSITIONS' is written in 'crystal' and the lattice matrix 'cell' is not equal to its transpose 'cell.T'. 

The 'cell' matrix is not supposed to be transposed when converting the fractional coordinate to cartesian coordinate.

**dpdata Version**

0.2.5

**Links**

https://github.com/deepmodeling/dpdata/blob/master/dpdata/qe/scf.py#L73

**Comment by wanghan-iapcm** [comment]
@Liu-RX Could you please take a look? Thanks!

**Comment by Liu-RX** [comment]
> @Liu-RX Could you please take a look? Thanks!

I will fix the issue.

**Comment by Liu-RX** [comment]
I have checked the code and I think it should be `coord = np.matmul(coord, cell)` rather than `coord = np.matmul(coord, cell.T)`? I will fix it in the next pr.
