### ISSUE TITLE
[Feature Request] to support multiple versions of cp2k

### ISSUE THREAD

**Issue by HuangJiameng** [deepmodeling/dpdata#326]
**Summary**

to support multiple versions of cp2k

**Detailed Description**

[https://github.com/deepmodeling/dpdata/discussions/323](url)
For popular versions of cp2k, related output.py are demanded.

**Comment by HuangJiameng** [comment]
@robinzyb Just a kindly reminder, what is the progress of supporting CP2K versions 8.1 and 9.1?

**Comment by robinzyb** [comment]
> @robinzyb Just a kindly reminder, what is the progress of supporting CP2K versions 8.1 and 9.1?
see here. I have write a new plugin for dpdata. 
https://github.com/robinzyb/cp2kdata
[Plug-in for dpdata](https://github.com/deepmodeling/dpdata/issues/326#plug-in-for-dpdata)

support version include 6.1 7.1 8.1 and 9.0.

**Comment by wanghan-iapcm** [comment]
What is the best way of officially support cp2kdata in dpdata ? @HuangJiameng @njzjz

**Comment by njzjz** [comment]
> What is the best way of officially support cp2kdata in dpdata ?

It's fine to add it to the dependencies or optional dependencies, depending on what you want it to be.

**Comment by wanghan-iapcm** [comment]
cp2kdata depends on dpdata, it would introduce a cyclic dependency

**Comment by HuangJiameng** [comment]
I haven't figured out why cp2kdata can support cp2k v8.1/9.1 yet, since I only find unit test for v6.1/7.1 in https://github.com/robinzyb/cp2kdata/tree/devel/tests/test_dpdata @robinzyb

**Comment by robinzyb** [comment]
you can find all versions under this directory [cp2kdata](https://github.com/robinzyb/cp2kdata/tree/devel)/[tests](https://github.com/robinzyb/cp2kdata/tree/devel/tests)/test_energy_force/. Files in test_dpdata are the files copied from original dpdata repository to test compatibility. It would be great If anyone can provide cp2k outputs with different versions  as my test files.

**Comment by njzjz** [comment]
It's fine to throw an error when the cp2k version is not supported.

```py
if version > supported_version:
    raise RuntimeError(
        "This CP2k version is not supported. Try the dpdata plugin from "
        "https://github.com/robinzyb/cp2kdata"
    )
```

**Comment by robinzyb** [comment]
Multiple versions and comprehensive tests are done by `cp2kdata`. 
and the deprecation warning was added https://github.com/deepmodeling/dpdata/pull/558

Is there anything else to do to resolve this issue?
