### ISSUE TITLE
Code format 

### ISSUE THREAD

**Issue by zezhong-zhang** [deepmodeling/dpdata#344]
**Summary**

Do we have a general python format guideline (i.e. Black)?  I noticed some format difference between files. If I use a format plugin in vscode, the actually code changes can be mixed with the format changes which can be confusing. Maybe we can fix the format issue in one commit and use a format workflow for all the following codes submitted.

**Comment by njzjz** [comment]
Generally, we may follow the DeePMD-kit documentation https://docs.deepmodeling.com/projects/deepmd/en/master/development/coding-conventions.html. Further, we can make a rule for all projects in the DeepModeling community.

cc @likefallwind, do you think it's necessary to discuss it?

**Comment by likefallwind** [comment]
> Generally, we may follow the DeePMD-kit documentation https://docs.deepmodeling.com/projects/deepmd/en/master/development/coding-conventions.html. Further, we can make a rule for all projects in the DeepModeling community.
> 
> cc @likefallwind, do you think it's necessary to discuss it?

I'm not sure, maybe we should take this advice to TOC member to discuss.

**Comment by likefallwind** [comment]
cc @amcadmus @jameswind @mohanchen @zjgemi what do you think? Maybe each TEAM has its own format guideline? Or we have a rule for all projects?

**Comment by njzjz** [comment]
#413 should be a nice resolution to format a project.
