### ISSUE TITLE
Error with converting CP2K AIMD_output

### ISSUE THREAD

**Issue by yunjian-hash** [deepmodeling/dpdata#378]
Dear developers,

When I use dpdata to convert CP2K data, there is an error reporting that the energy in log file does not match that in pos file. I printed out the energy and found that the next frame the last normally converted  energy  is not the energy of the error report, how can I solve this problem? How can I output the step of the frame where the error was reported? 

In addition to that, will cp2k's energy with low precision floating point lead to significant data errors

![f90ece5203addaa35359f67a47e37c6](https://user-images.githubusercontent.com/75162924/203703707-eb9dffa8-4d38-40b0-92ba-7d8e4f4b97c1.png)

**Comment by robinzyb** [comment]
I recommend to use the package https://github.com/robinzyb/cp2kdata#plug-in-for-dpdata
for detail, see
https://github.com/deepmodeling/dpdata/discussions/374#discussioncomment-4207241

**Comment by yunjian-hash** [comment]
> 

When I use Cp2kData, there is still an error.

![019f7f3db546a1d6a8093708d7942d4](https://user-images.githubusercontent.com/75162924/203706972-876d5b4a-6fe1-4578-b898-15556e4f7ff0.png)

here is the dpdata python script:

from dpdata import System, LabeledSystem, MultiSystems
import numpy as np

####### 读入轨迹 #######
ls1=LabeledSystem('./Walker_0', cp2k_output_name='cp2k.log', fmt="cp2kdata/md")
ls2=LabeledSystem('./Walker_1', cp2k_output_name='cp2k.log', fmt="cp2kdata/md")
ls3=LabeledSystem('./Walker_2', cp2k_output_name='cp2k.log', fmt="cp2kdata/md")

####### 验证集结构数 #######
#a1 = np.random.choice(len(ls1),size=30,replace=False)	#随机选100个作测试集
a2 = np.random.choice(len(ls2),size=30,replace=False)
a3 = np.random.choice(len(ls3),size=40,replace=False)

####### 训练集结构数  #######
#w1 = list(set(range(1,len(ls1)))-set(a1))[10:-1:30]
w2 = list(set(range(1,len(ls2)))-set(a2))[10:-1:15]
w3 = list(set(range(1,len(ls3)))-set(a3))[10:-1:15]

####### 训练集 #######
ms= MultiSystems() 
#ms.append(ls1.sub_system(w1)) 
ms.append(ls2.sub_system(w2))
ms.append(ls3.sub_system(w3)) 

ms.to_deepmd_raw('deepmd')
ms.to_deepmd_npy('deepmd',set_size=5000)

#print('There are %d frames for training' % len(ls1.sub_system(w1)))
print('There are %d frames for training' % len(ls2.sub_system(w2)))
print('There are %d frames for training' % len(ls3.sub_system(w3)))


####### 测试集 #######
v= MultiSystems() 
#v.append(ls1.sub_system(a1)) 
v.append(ls2.sub_system(a2))
v.append(ls3.sub_system(a3)) 

v.to_deepmd_raw('deepmd_validation')
v.to_deepmd_npy('deepmd_validation',set_size=300)

#print('There are %d frames for validation' % len(ls1.sub_system(a1)))
print('There are %d frames for validation' % len(ls2.sub_system(a2)))
print('There are %d frames for validation' % len(ls3.sub_system(a3)))

**Comment by robinzyb** [comment]
Hi, can you provide an `input` and `log` file, I can use it to debug the version problem

**Comment by yunjian-hash** [comment]
> 

The log and pos files are too big to be uploaded at here. How can I give you?

**Comment by robinzyb** [comment]
the full log won't be necessary. You may run a MD with 3 steps

**Comment by yunjian-hash** [comment]
> the full log won't be necessary. You may run a MD with 3 steps

In fact, the error only happens for epecific trajectories. The dpdata can convert most of my trajectories. I am just so confused why there is an error for this trajectories and can not find where is the problem after being checked carefully.

**Comment by robinzyb** [comment]
Did you mean using the fmt='cp2kdata/md' or original 'cp2k/aimd_output'?
You can provide two files, one is parsable and the other one is unparsable.

**Comment by yunjian-hash** [comment]
> Did you mean using the fmt='cp2kdata/md' or original 'cp2k/aimd_output'? You can provide two files, one is parsable and the other one is unparsable.

Both of fmt='cp2kdata/md' and original 'cp2k/aimd_output' do not work. For the first one, I know the reason is that I do not print force information in the MOTION section,but in FORCE_EVAL section and thus the force information is in the log file, not frc file.

How can I give you the file, through the email or other ways? Thanks!

**Comment by DM0815** [comment]
> I recommend to use the package https://github.com/robinzyb/cp2kdata#plug-in-for-dpdata for detail, see [#374 (reply in thread)](https://github.com/deepmodeling/dpdata/discussions/374#discussioncomment-4207241)

How can I install cp2k when offline

**Comment by robinzyb** [comment]
you can attach the log file in GitHub

**Comment by PolyuWeldingSpock** [comment]
> you can attach the log file in GitHub

Hi, have this problem been solved?

**Comment by robinzyb** [comment]
The newest version of cp2kdata probably solves the problem
https://github.com/robinzyb/cp2kdata/issues/15

**Comment by robinzyb** [comment]
> > Did you mean using the fmt='cp2kdata/md' or original 'cp2k/aimd_output'? You can provide two files, one is parsable and the other one is unparsable.
> 
> Both of fmt='cp2kdata/md' and original 'cp2k/aimd_output' do not work. For the first one, I know the reason is that I do not print force information in the MOTION section,but in FORCE_EVAL section and thus the force information is in the log file, not frc file.
> 
> How can I give you the file, through the email or other ways? Thanks!

@yunjian-hash  
cp2kdata now is able to parse atomic forces in log files. 
https://github.com/deepmodeling/dpdata/discussions/354#discussioncomment-6972016
