### ISSUE TITLE
[BUG]Dpdata-Gaussian Error

### ISSUE THREAD

**Issue by wuxxuu** [deepmodeling/dpdata#404]
Dear developers,

Here is the error when I try to convert Gaussian's log file by using dpdata: 

[![51672127229_ pic](https://user-images.githubusercontent.com/106394795/209639184-4be44115-251a-4c6a-8e18-5735d5eab289.png)](url)

Does anyone know what happened? Thanks!

**Comment by HuangJiameng** [comment]
Could you attach the file "opt-3AO-UO2-1.log"?

**Comment by HuangJiameng** [comment]
Why is `coords` appended when getting `forces`? @njzjz https://github.com/deepmodeling/dpdata/commit/c481a0d7f58b4ecda54ee5ca5b71c53d7611a08e

**Comment by njzjz** [comment]
The input orientation is not printed, so it failed to read and store coordinates. To print input orientation, use [`Geom=PrintInputOrient`](https://gaussian.com/geom/) keyword.
