### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by Taixi-Feng** [deepmodeling/dpdata#435]
When I use dpdata package to process OUTCAR an error is reported. Sorry, I don't know how to deal with it. Thank you for your answer. 
![ad2c5e08bc3b33133a42b418c7dcc17](https://user-images.githubusercontent.com/104333661/226528572-f6124e6f-7faa-49ad-8223-064a07ef132f.png)

**Comment by wanghan-iapcm** [comment]
The same issue as https://github.com/deepmodeling/dpdata/discussions/434 ?

**Comment by Taixi-Feng** [comment]
The problem I raised has been solved with your help. Thank you very much
