### ISSUE TITLE
[BUG]when cutting a dataset of cp2k/aimd, the command of data.sub_system made such a bug.

### ISSUE THREAD

**Issue by jiaweiGe472** [deepmodeling/dpdata#439]
>>> import dpdata
i>>> import numpy as np
>>> data = dpdata.LabeledSystem(".",fmt="cp2k/aimd_output")
>>> print('# the data contains %d frames' % len(data))
# the data contains 501 frames
>>> index_validation = np.random.choice(500,size=40,replace=False)
>>> index_training = list(set(range(501))-set(index_validation))
>>> data_training = data.sub_system(index_training)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public1/home/sc61116/.conda/envs/sc61116/lib/python3.9/site-packages/dpdata/system.py", line 1193, in sub_system
    tmp_sys.data['forces'] = self.data['forces'][f_idx].reshape(-1, self.data['forces'].shape[1], 3)
ValueError: cannot reshape array of size 0 into shape (0,3)

**Comment by robinzyb** [comment]
hi, can you provide the aimd files so that I can reproduce the error

**Comment by jiaweiGe472** [comment]
hi, I have uploaded my aimd files on github. Because of the limitation of mail on enclosed files, I used github to load my aimd files. Thank you for your help.

荷露斯之眸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepmodeling/dpdata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 中午1:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deepmodeling/dpdata] [BUG]when cutting a dataset of cp2k/aimd, the command of data.sub_system made such a bug. (Issue #439)





 
hi, can you provide the aimd files so that I can reproduce the error

**Comment by robinzyb** [comment]
Hello, I cannot find the FORCES in your `xxx.log files`, which are required by fmt="cp2k/aimd_output". However, if you have had -frc-1.xyz files, you can use cp2kdata with dpdata and set fmt='cp2kdata/md'. see https://github.com/deepmodeling/dpdata/issues/378 for detail

**Comment by jiaweiGe472** [comment]
>>> ls1=LabeledSystem('/public1/home/sc61116/cp2k/wanhao/20230323/1CELL/MD',fmt="cp2kdata/md")Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public1/home/sc61116/.conda/envs/sc61116/lib/python3.9/site-packages/dpdata/system.py", line 944, in __init__
    self.from_fmt(file_name, fmt, type_map=type_map, begin= begin, step=step)
  File "/public1/home/sc61116/.conda/envs/sc61116/lib/python3.9/site-packages/dpdata/system.py", line 135, in from_fmt
    raise RuntimeError('unknow data format ' + fmt)
RuntimeError: unknow data format cp2kdata/md


now, I still meet a error. When I import  "ls1=LabeledSystem('/public1/home/sc61116/cp2k/wanhao/20230323/1CELL/MD',fmt="cp2kdata/md")", it displayed a unknown data format.

**Comment by robinzyb** [comment]
have you installed the cp2kdata package?

**Comment by jiaweiGe472** [comment]
yes，I have installed cp2kdata. when importing "data=dpdata.LabeledSystem(".",fmt="cp2k/aimd_output")", it is ok. But when importing "data=dpdata.LabeledSystem,fmt="cp2kdata/md"", it displayed a mistake.

**Comment by robinzyb** [comment]
could you check the installation using `pip show cp2kdata`?

**Comment by jiaweiGe472** [comment]
(sc61116) [sc61116@ln91%bscc-m MD]$ pip show cp2kdata
Name: Cp2kData
Version: 0.4.1
Summary: Small Package to Postprocessing Cp2k Output
Home-page: https://github.com/robinzyb/cp2kdata
Author: Yongbin Zhuang
Author-email: robinzhuang@stu.xmu.edu.com
License: 
Location: /public1/home/sc61116/.conda/envs/sc61116/lib/python3.9/site-packages
Requires: dpdata, numpy, scipy, pytest, pytest-cov, matplotlib, regex, ase, click
Required-by: 


Yes， I have checked it. And it determines Cp2kData existes.

**Comment by robinzyb** [comment]
Did you install from pip directly like `pip install cp2kdata` or install from source code, for example, `git clone ..`, then `cd cp2kdata` and `pip install .`

**Comment by jiaweiGe472** [comment]
Now, I have solved it, not because cp2kdata. I set the print_level as high. And I get these files of cp2k-1.ener, cp2k-pos-1.xyz, cp2k-frc-1.xyz and cp2k-1.stress. Thus, these files is met. Furthermore, I want to know how to close down some output files, such hartree, efield  and so on.

**Comment by jiaweiGe472** [comment]
Now, I have solved it, not because cp2kdata. I set the print_level as high. And I get these files of cp2k-1.ener, cp2k-pos-1.xyz, cp2k-frc-1.xyz and cp2k-1.stress. Thus, these files is met. Furthermore, I want to know how to close down some output files, such hartree, efield  and so on.

**Comment by jiaweiGe472** [comment]
Now, I have solved it, not because cp2kdata. I set the print_level as high. And I get these files of cp2k-1.ener, cp2k-pos-1.xyz, cp2k-frc-1.xyz and cp2k-1.stress. Thus, these files is met. Furthermore, I want to know how to close down some output files, such hartree, efield  and so on.

**Comment by robinzyb** [comment]
in the motion section:
```
  &PRINT
   &TRAJECTORY
     &EACH
       MD 1
     &END EACH
   &END TRAJECTORY
   &VELOCITIES
     &EACH
       MD 1
     &END EACH
   &END VELOCITIES
   &FORCES
     &EACH
       MD 1
     &END EACH
   &END FORCES

```
this will only output pos-1, frc-1, vel-1 files.

**Comment by robinzyb** [comment]
@amcadmus it seems this problem has solved. Please close this issue. Thank you
