### ISSUE TITLE
an error processing AIMD data for CP2K

### ISSUE THREAD

**Issue by caojiachun** [deepmodeling/dpdata#462]
Hello:
I encountered an error when running dpdata to process the cp2k_aimd task data:
'>>> ls=LabeledSystem("cp2k.log",fmt='cp2k/aimd_output')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/home/2001_aozhimin/apps/deepmd-kit-cpu/lib/python3.10/site-packages/dpdata/system.py", line 226, in __init__
    self.from_fmt(file_name, fmt, type_map=type_map, begin= begin, step=step, **kwargs)
  File "/nfs/home/2001_aozhimin/apps/deepmd-kit-cpu/lib/python3.10/site-packages/dpdata/system.py", line 252, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
  File "/nfs/home/2001_aozhimin/apps/deepmd-kit-cpu/lib/python3.10/site-packages/dpdata/system.py", line 1012, in from_fmt_obj
    data = fmtobj.from_labeled_system(file_name, **kwargs)
  File "/nfs/home/2001_aozhimin/apps/deepmd-kit-cpu/lib/python3.10/site-packages/dpdata/plugins/cp2k.py", line 10, in from_labeled_system
    xyz_file = sorted(glob.glob("{}/*pos*.xyz".format(file_name)))[0]
IndexError: list index out of range
'
[cp2k.zip](https://github.com/deepmodeling/dpdata/files/11355425/cp2k.zip)

**Comment by robinzyb** [comment]
hi,
You can try the cp2kdata package. 
please check out this issue:https://github.com/deepmodeling/dpdata/issues/378.
If you use cp2kdata package, make sure the -pos-1.xyz,-1.ener and -frc-1.xyz files are included in the cp2k MD directory

**Comment by PolyuWeldingSpock** [comment]
Hi,

Have you solved this problem? I have faced the same issue.

**Comment by robinzyb** [comment]
@njzjz @PolyuWeldingSpock The `zip` file doesn't contain necessary files for me to parse. and I am not longer to maintain the original MD parser because it supports limited versions and compliated the problems

**Comment by caojiachun** [comment]
> 

I copied the key file for recalculation and did not have the problem. It seems to be an occasional error.

**Comment by caojiachun** [comment]
> Hi,
> 
> Have you solved this problem? I have faced the same issue.

I copied the key file for recalculation and did not have the problem. It seems to be an occasional error.

**Comment by robinzyb** [comment]
> > Hi,
> > Have you solved this problem? I have faced the same issue.
> 
> I copied the key file for recalculation and did not have the problem. It seems to be an occasional error.

Hello,
Did you solve this by using cp2kdata or cp2k/aimd fmt?

**Comment by robinzyb** [comment]
I see. The code will check the xyz files under the directories you specified. It seems the problem has been solved. I will close it now

**Comment by PolyuWeldingSpock** [comment]
> > > > Hi,
> > > > Have you solved this problem? I have faced the same issue.
> > > 
> > > 
> > > I copied the key file for recalculation and did not have the problem. It seems to be an occasional error.
> > 
> > 
> > Hello, Did you solve this by using cp2kdata or cp2k/aimd fmt?
> 
> I didn't change it.

Hi,
which version of cp2k did you use?

**Comment by caojiachun** [comment]
> > > > > Hi,
> > > > > Have you solved this problem? I have faced the same issue.
> > > > 
> > > > 
> > > > I copied the key file for recalculation and did not have the problem. It seems to be an occasional error.
> > > 
> > > 
> > > Hello, Did you solve this by using cp2kdata or cp2k/aimd fmt?
> > 
> > 
> > I didn't change it.
> 
> Hi, which version of cp2k did you use?

7.10 version

**Comment by njzjz** [comment]
> and I am not longer to maintain the original MD parser because it supports limited versions and compliated the problems

@robinzyb I suggest adding a message when the version is not supported, as I said in #236.
