### ISSUE TITLE
[BUG] _dpdata cannot recognize the cp2k9.1 output file_

### ISSUE THREAD

**Issue by Zhihaoiee** [deepmodeling/dpdata#486]
**Summary**

I tried to use dpdata.LabeledSystem to deal with a cp2k9.1 output file, but dpdata can hardly recognize the file content.
(![image](https://github.com/deepmodeling/dpdata/assets/92719845/7d349b8b-2a9c-4cf4-9e64-f1ec7ef4996c))

Version of software:
Python 3.10.6 (apt-get)
dpdata 0.2.15 (pip)

commands:
>>> import dpdata
>>> data = dpdata.LabeledSystem('./out-cp2k', fmt = 'cp2k/aimd_output')
>>> data
Data Summary
Labeled System
-------------------
Frame Numbers      : 0
Atom Numbers       : 0
Including Virials  : No
Element List       :
-------------------

Platform:

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023
Ubuntu 22.04.2 LTS

**Steps to Reproduce**

**Further Information, Files, and Links**
[out-cp2k.zip](https://github.com/deepmodeling/dpdata/files/11800941/out-cp2k.zip)

**Comment by Zhihaoiee** [comment]
[https://github.com/deepmodeling/dpdata/issues/378](url)
Cp2kData works!

**Comment by robinzyb** [comment]
Yes, Why did you reopen ?
