### ISSUE TITLE
After installing cp2kdata, the trajectory with an MD of 100 Although the trajectory can be read But throw an error:dpdata.system.DataError: Shape of coords is (51, 130, 3), but expected (5001, 130, 3

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/dpdata#543]
After installing cp2kdata, the trajectory with an MD of 100 Although the trajectory can be read But throw an error:dpdata.system.DataError: Shape of coords is (51, 130, 3), but expected (5001, 130, 3),The default MD is still 1

**Comment by robinzyb** [comment]
hello, could you upload the error messages after you executed the code ?

**Comment by hanrm94** [comment]
> hello, could you upload the error messages after you executed the code ?

Hello, I have a similar question and hope to get your  help.
The reference file is too large to upload. If you need it, you can contact me with this email rongmei_h1351878@163.com
<img width="639" alt="error" src="https://github.com/deepmodeling/dpdata/assets/133116023/063cd8c6-2323-42c9-98e4-6ed5f5d9674c">

**Comment by robinzyb** [comment]
Do you have inconsistent number of output in `-1.ener` and `-pos-1.xyz` files? for example, the `-1.ener` has 5000 values(5000line) and the `-pos-1.xyz` has only 50 structures

**Comment by hanrm94** [comment]
@robinzyb Thank you for your reply.I will try to modify my initial file.

**Comment by robinzyb** [comment]
> @robinzyb Thank you for your reply.I will try to modify my initial file.

Is the problem solved?

**Comment by hanrm94** [comment]
> > @robinzyb Thank you for your reply.I will try to modify my initial file.
> 
> Is the problem solved?

It hasn't been solved yet. 
I'm trying to see if I can change which part of the cp2k input file makes 5000 values in the output -1.ener file 5000 values.
Since I am a beginner and not familiar with these software and programs, can my idea be realized?

**Comment by hanrm94** [comment]
> > @robinzyb Thank you for your reply.I will try to modify my initial file.
> 
> Is the problem solved?

It hasn't been solved yet.
I'm trying to see if I can change which part of the cp2k input file goes from 5000 values to 50 values in the output -1.ener file.
Since I am a beginner and not familiar with these software and programs, can my ideas be realized?

**Comment by robinzyb** [comment]
> > > @robinzyb Thank you for your reply.I will try to modify my initial file.
> > 
> > 
> > Is the problem solved?
> 
> It hasn't been solved yet. I'm trying to see if I can change which part of the cp2k input file goes from 5000 values to 50 values in the output -1.ener file. Since I am a beginner and not familiar with these software and programs, can my ideas be realized?

No need, just move out the -1.ener, the cp2kdata will parse energy from -pos-1.xyz as well.

**Comment by hanrm94** [comment]
> > > > @robinzyb Thank you for your reply.I will try to modify my initial file.
> > > 
> > > 
> > > Is the problem solved?
> > 
> > 
> > It hasn't been solved yet. I'm trying to see if I can change which part of the cp2k input file goes from 5000 values to 50 values in the output -1.ener file. Since I am a beginner and not familiar with these software and programs, can my ideas be realized?
> 
> No need, just move out the -1.ener, the cp2kdata will parse energy from -pos-1.xyz as well.

Thank you very much for your help, my problem is solved.
