### ISSUE TITLE
When using dpdata to convert the CP2K output file into an MD executable file, it can be converted when the MD in CP2K-inp is 1, but when the MD is converted to 100, the following error occurs:AssertionError

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/dpdata#544]
When using dpdata to convert the CP2K output file into an MD executable file, it can be converted when the MD in CP2K-inp is 1, but when the MD is converted to 100, the following error occurs:
AssertionError:(array(1-17432.236] dtype=FLoat32). array(i-17430.65], dtype=float32), "There may be errors in the file')

The reference file is too large to upload. If you need it, you can contact me with this email xufangfei@dp.tech

**Comment by Taixi-Feng** [comment]
This answer may be helpful to you #378
