### ISSUE TITLE
the result is empty when dpdata complete the task of converting the data of cp2k to the data of deepmd

### ISSUE THREAD

**Issue by 12jscvb** [deepmodeling/dpdata#556]
Data Summary
Labeled System
-------------------
Frame Numbers      : 0
Atom Numbers       : 0
Including Virials  : No
Element List       :
-------------------

how could I solve the problem Thank you for help

**Comment by robinzyb** [comment]
did the scf of cp2k output converge?

**Comment by 12jscvb** [comment]
yes, I have the output.log file through cp2k AIMD simulation ,so I want to convert this file to that deepmd needs

**Comment by 12jscvb** [comment]
> did the scf of cp2k output converge?

Data Summary
Labeled System
-------------------
Frame Numbers      : 0
Atom Numbers       : 0
Including Virials  : No
Element List       :
-------------------


> yes, I have the output.log file through cp2k AIMD simulation ,so I want to convert this file to that deepmd needs



> did the scf of cp2k output converge?

yes, I have the output.log file through cp2k AIMD simulation ,so I want to convert this file to that deepmd needs
[out.zip](https://github.com/deepmodeling/dpdata/files/13042684/out.zip)

**Comment by 12jscvb** [comment]
yes .I have get the output.log through the cp2k AIMD simulation. I want to convert this file to that deepmd needs. but the result is empty. Could you help me ?Thank you very much



---Original---
From: "Yongbin ***@***.***&gt;
Date: Thu, Oct 19, 2023 20:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deepmodeling/dpdata] the result is empty when dpdata completethe task of converting the data of cp2k to the data of deepmd (Issue #556)




 
did the scf of cp2k output converge?

**Comment by 12jscvb** [comment]
> 你好，out.zip只包含来自Lamm ps的模型开发
sorry. I do not understand your meaning .what file I need to provide ?  either. the output file is not correct.

**Comment by robinzyb** [comment]
I need output.log from cp2k which is not included in your provided files.

**Comment by 12jscvb** [comment]
> I need output.log from cp2k which is not included in your provided files.

Sorry, I'll send it to you again. Thank you very much for your help

[output.zip](https://github.com/deepmodeling/dpdata/files/13048550/output.zip)

**Comment by robinzyb** [comment]
hello, I found this is MD simulation from cp2k. in this directory/folder, do you find `-1.ener` `-pos-1.xyz`, `-frc-1.xyz` files?  if so please send upload as well.

**Comment by 12jscvb** [comment]
> hello, I found this is MD simulation from cp2k. in this directory/folder, do you find `-1.ener` `-pos-1.xyz`, `-frc-1.xyz` files? if so please send upload as well.

I'm so sorry. It's my fault. I appreciate your patience. Here are all my output files.
[cp2kout.zip](https://github.com/deepmodeling/dpdata/files/13054989/cp2kout.zip)

**Comment by robinzyb** [comment]
It works very well. Could you try install cp2kdata and use dpdata plugin?

```python
import dpdata
cp2kmd_dir = "./55-20rfj2"
cp2kmd_output_name = "1.out"
dp = dpdata.LabeledSystem(cp2kmd_dir, cp2k_output_name=cp2kmd_output_name, fmt="cp2kdata/md")
print(dp)
```
```shell
--- You are parsing data using package Cp2kData ---
Parsing Energies From ./55-20rfj2/aimd-1.ener
Parsing Structures From ./55-20rfj2/aimd-pos-1.xyz
Parsing Froces From ./55-20rfj2/aimd-frc-1.xyz
Parsing Cells Information from ./55-20rfj2/1.out
Atom names are fake chemical symbols as you set in cp2k input.
--- You are parsing data using package Cp2kData ---
Data Summary
Labeled System
-------------------
Frame Numbers      : 201
Atom Numbers       : 255
Including Virials  : No
Element List       :
-------------------
Al  N  H  Cl  O
55  20  80  20  80

```

**Comment by 12jscvb** [comment]
Thank you very much .Can I add your contact information? I really want to meet you . This is my WeChat account&nbsp; jx13291000695



---Original---
From: "Yongbin ***@***.***&gt;
Date: Fri, Oct 20, 2023 23:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deepmodeling/dpdata] the result is empty when dpdata completethe task of converting the data of cp2k to the data of deepmd (Issue #556)




 
It works very well. Could you try install cp2kdata and use dpdata plugin?
 import dpdata cp2kmd_dir = "./55-20rfj2" cp2kmd_output_name = "1.out" dp = dpdata.LabeledSystem(cp2kmd_dir, cp2k_output_name=cp2kmd_output_name, fmt="cp2kdata/md") print(dp)
 --- You are parsing data using package Cp2kData --- Parsing Energies From ./55-20rfj2/aimd-1.ener Parsing Structures From ./55-20rfj2/aimd-pos-1.xyz Parsing Froces From ./55-20rfj2/aimd-frc-1.xyz Parsing Cells Information from ./55-20rfj2/1.out Atom names are fake chemical symbols as you set in cp2k input. --- You are parsing data using package Cp2kData --- Data Summary Labeled System ------------------- Frame Numbers      : 201 Atom Numbers       : 255 Including Virials  : No Element List       : ------------------- Al  N  H  Cl  O 55  20  80  20  80

**Comment by robinzyb** [comment]
Sorry Just keep it in Github. Also, are your problem solved?

**Comment by 12jscvb** [comment]
yes. it has been solved succwas fully&nbsp; &nbsp;Thank you !



---Original---
From: "Yongbin ***@***.***&gt;
Date: Sat, Oct 21, 2023 08:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deepmodeling/dpdata] the result is empty when dpdata completethe task of converting the data of cp2k to the data of deepmd (Issue #556)




 
Sorry Just keep it in Github. Also, are your problem solved?
