### ISSUE TITLE
dp data cannot translate OUTCAR results in machine learning AIMD(MLAIMD)

### ISSUE THREAD

**Issue by Suyoung999999999** [deepmodeling/dpdata#586]
### Summary

How to solve machine learning AIMD data into dpmd training data?

### Detailed Description

Using machine learning AIMD for calculation will speed up the data preparation in the early stage of dpmd. However, I found that all frames could not be identified when using dpdata for format conversion. For example, I conducted an MLAIMD with 30,000 steps, but dpdata could only identify 269 of them. These 269 data were run without machine learning. So please ask how to use python script to achieve this feature, can you provide a python script?

**Comment by wanghan-iapcm** [comment]
Could you please provide an example (the minimal one should be enough) output that may reproduce the issue? thanks!

**Comment by Suyoung999999999** [comment]
Dear Professor Wang,
Hello! The attachment below is my OUTCAR file using machine learning AIMD (MLAIMD). All data points cannot be converted using dp data, which may be the part that does not recognize machine learning.
[OUTCAR.zip](https://github.com/deepmodeling/dpdata/files/13594547/OUTCAR.zip)
[有关dp data如何实现ML-AIMD的数据转化-苏阳.pptx](https://github.com/deepmodeling/dpdata/files/13594550/dp.data.ML-AIMD.-.pptx)

**Comment by Suyoung999999999** [comment]
Dear Professor Wang,
          Hello! I have uploaded an example on Github and look forward to your reply


| |
su18812625523
|
|
***@***.***
|
On 12/7/2023 09:14，Han ***@***.***> wrote：

Could you please provide an example (the minimal one should be enough) output that may reproduce the issue? thanks!

**Comment by wanghan-iapcm** [comment]
I find only 187 frames of your trajectory were labeled by dft, while other frames were labeled by ML. 
dpdata correctly load the 187 dft frames. 

It does not make much to train against ML energy and forces. If you really need them you may modify [this file ](https://github.com/deepmodeling/dpdata/blob/devel/dpdata/vasp/outcar.py).

**Comment by Suyoung999999999** [comment]
Thanks for your reply


| |
su18812625523
|
|
***@***.***
|
On 12/13/2023 14:18，Han ***@***.***> wrote：

I find only 187 frames of your trajectory were labeled by dft, while other frames were labeled by ML.
dpdata correctly load the 187 dft frames.

It does not make much to train against ML energy and forces. If you really need them you may modify this file .

**Comment by njzjz** [comment]
It has been supported by #282.
