### ISSUE TITLE
[Feature Request] ASE's traj format 

### ISSUE THREAD

**Issue by thangckt** [deepmodeling/dpdata#610]
### Summary

Dear Developers, 

I wonder if dpdata can input [ASE's traj](https://wiki.fysik.dtu.dk/ase/ase/io/trajectory.html) ?

### Detailed Description

Thank you

**Comment by QuantumMisaka** [comment]
I do think this is needed, for ASE traj format can widely used for ASE mission, and in which lots of property information will be stored.

Traj file can be LabeledSystem or MultiSystems
