### ISSUE TITLE
[BUG] The LabeledSystem would raise error when the abacus log file does not contain force

### ISSUE THREAD

**Issue by floatingCatty** [deepmodeling/dpdata#662]
### Bug summary

This is caused by the get_force function in 
![image](https://github.com/deepmodeling/dpdata/assets/64253517/b3e05143-4da8-4e27-919c-960a57947b39)
would return an empty list [[]] if the log does not contain force data. Then, calling np.newaxis would raise an error.

### dpdata Version

0.2.17

### Input Files, Running Commands, Error Log, etc.

![image](https://github.com/deepmodeling/dpdata/assets/64253517/b52cdeff-2971-4955-be85-a6ecd6be47a3)

### Steps to Reproduce

Just calling LabledSystem on abacus scf output without setting the cal_force tag would do.

**Comment by njzjz** [comment]
The function may need a better error message. `LabeledSystem` always needs the force as it's designed for machine learning.

**Comment by floatingCatty** [comment]
Yeah, but not all machine learning task using DFT data are dependent on
force and energy. Therefore, this error may prohibit people who using
dpdata as a post processing tool of structure information.

Jinzhe Zeng ***@***.***> 于2024年5月31日周五 13:44写道：

**Comment by pxlxingliang** [comment]
This bug will fixed in https://github.com/deepmodeling/dpdata/pull/669
