### ISSUE TITLE
xyz data mistaken as containing 'virials'

### ISSUE THREAD

**Issue by Feiyang472** [deepmodeling/dpdata#74]
When using dpdata I found that MultiSystems kept thinking I had 'virials' in my data, when actually I didn't.

`system.py line 1292
Object of type Nonetype has no len()`

I circumvented this issue by adding a `data['virials'] is not None` check everytime a related error was reported.

Would someone like to explain where (and why) `'virials'` is added as a key in `self.data` by default?

**Comment by amcadmus** [comment]
Thank you for reporting the bug, we will fix it asap.

Could you please kindly provide the minimal data file that can reproduce the bug?

**Comment by Feiyang472** [comment]
> Thank you for reporting the bug, we will fix it asap.
> 
> Could you please kindly provide the minimal data file that can reproduce the bug?

Thank you for your reply. Here's a typical working xyz file in gap training. You'll notice that it doesn't contain virials data. Unfortunately, I modified your code here and there so could not reproduce error logs that would have emerged with a fresh clone.

Thanks again for your attention.

`81
Lattice="9.312844978309194 0.0 0.0 0.0 9.312844978309194 0.0 0.0 0.0 9.312844978309194" Properties=species:S:1:pos:R:3:forces:R:3 pbc="T T T" energy=71.71319028943992
O       0.00000000       0.00000000       0.11926200      -0.00000000      -0.00000000       8.11183591 
H       0.00000000       0.76323900       8.83579798       0.00000000       5.21893682      -4.05591796 
H       0.00000000       8.54960598       8.83579798       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       0.00000000       3.22354366      -0.00000000       0.00000000       8.11183591 
H       0.00000000       0.76323900       2.62723466       0.00000000       5.21893682      -4.05591796 
H       0.00000000       8.54960598       2.62723466       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       0.00000000       6.32782532      -0.00000000       0.00000000       8.11183591 
H       0.00000000       0.76323900       5.73151632       0.00000000       5.21893682      -4.05591796 
H       0.00000000       8.54960598       5.73151632       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       3.10428166       0.11926200      -0.00000000       0.00000000       8.11183591 
H       0.00000000       3.86752066       8.83579798       0.00000000       5.21893682      -4.05591796 
H       0.00000000       2.34104266       8.83579798       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       3.10428166       3.22354366      -0.00000000      -0.00000000       8.11183591 
H       0.00000000       3.86752066       2.62723466       0.00000000       5.21893682      -4.05591796 
H       0.00000000       2.34104266       2.62723466       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       3.10428166       6.32782532      -0.00000000      -0.00000000       8.11183591 
H       0.00000000       3.86752066       5.73151632       0.00000000       5.21893682      -4.05591796 
H       0.00000000       2.34104266       5.73151632       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       6.20856332       0.11926200      -0.00000000      -0.00000000       8.11183591 
H       0.00000000       6.97180232       8.83579798       0.00000000       5.21893682      -4.05591796 
H       0.00000000       5.44532432       8.83579798       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       6.20856332       3.22354366      -0.00000000      -0.00000000       8.11183591 
H       0.00000000       6.97180232       2.62723466       0.00000000       5.21893682      -4.05591796 
H       0.00000000       5.44532432       2.62723466       0.00000000      -5.21893682      -4.05591796 
O       0.00000000       6.20856332       6.32782532      -0.00000000      -0.00000000       8.11183591 
H       0.00000000       6.97180232       5.73151632       0.00000000       5.21893682      -4.05591796 
H       0.00000000       5.44532432       5.73151632       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       0.00000000       0.11926200      -0.00000000       0.00000000       8.11183591 
H       3.10428166       0.76323900       8.83579798      -0.00000000       5.21893682      -4.05591796 
H       3.10428166       8.54960598       8.83579798       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       0.00000000       3.22354366      -0.00000000       0.00000000       8.11183591 
H       3.10428166       0.76323900       2.62723466      -0.00000000       5.21893682      -4.05591796 
H       3.10428166       8.54960598       2.62723466       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       0.00000000       6.32782532      -0.00000000       0.00000000       8.11183591 
H       3.10428166       0.76323900       5.73151632      -0.00000000       5.21893682      -4.05591796 
H       3.10428166       8.54960598       5.73151632       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       3.10428166       0.11926200      -0.00000000       0.00000000       8.11183591 
H       3.10428166       3.86752066       8.83579798      -0.00000000       5.21893682      -4.05591796 
H       3.10428166       2.34104266       8.83579798       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       3.10428166       3.22354366      -0.00000000      -0.00000000       8.11183591 
H       3.10428166       3.86752066       2.62723466      -0.00000000       5.21893682      -4.05591796 
H       3.10428166       2.34104266       2.62723466       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       3.10428166       6.32782532      -0.00000000      -0.00000000       8.11183591 
H       3.10428166       3.86752066       5.73151632      -0.00000000       5.21893682      -4.05591796 
H       3.10428166       2.34104266       5.73151632       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       6.20856332       0.11926200      -0.00000000      -0.00000000       8.11183591 
H       3.10428166       6.97180232       8.83579798       0.00000000       5.21893682      -4.05591796 
H       3.10428166       5.44532432       8.83579798       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       6.20856332       3.22354366       0.00000000      -0.00000000       8.11183591 
H       3.10428166       6.97180232       2.62723466       0.00000000       5.21893682      -4.05591796 
H       3.10428166       5.44532432       2.62723466       0.00000000      -5.21893682      -4.05591796 
O       3.10428166       6.20856332       6.32782532      -0.00000000      -0.00000000       8.11183591 
H       3.10428166       6.97180232       5.73151632      -0.00000000       5.21893682      -4.05591796 
H       3.10428166       5.44532432       5.73151632       0.00000000      -5.21893682      -4.05591796 
O       6.20856332       0.00000000       0.11926200       0.00000000      -0.00000000       8.11183591 
H       6.20856332       0.76323900       8.83579798      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       8.54960598       8.83579798      -0.00000000      -5.21893682      -4.05591796 
O       6.20856332       0.00000000       3.22354366       0.00000000       0.00000000       8.11183591 
H       6.20856332       0.76323900       2.62723466      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       8.54960598       2.62723466      -0.00000000      -5.21893682      -4.05591796 
O       6.20856332       0.00000000       6.32782532       0.00000000       0.00000000       8.11183591 
H       6.20856332       0.76323900       5.73151632      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       8.54960598       5.73151632      -0.00000000      -5.21893682      -4.05591796 
O       6.20856332       3.10428166       0.11926200       0.00000000       0.00000000       8.11183591 
H       6.20856332       3.86752066       8.83579798      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       2.34104266       8.83579798       0.00000000      -5.21893682      -4.05591796 
O       6.20856332       3.10428166       3.22354366       0.00000000      -0.00000000       8.11183591 
H       6.20856332       3.86752066       2.62723466      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       2.34104266       2.62723466       0.00000000      -5.21893682      -4.05591796 
O       6.20856332       3.10428166       6.32782532       0.00000000      -0.00000000       8.11183591 
H       6.20856332       3.86752066       5.73151632      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       2.34104266       5.73151632      -0.00000000      -5.21893682      -4.05591796 
O       6.20856332       6.20856332       0.11926200       0.00000000      -0.00000000       8.11183591 
H       6.20856332       6.97180232       8.83579798      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       5.44532432       8.83579798      -0.00000000      -5.21893682      -4.05591796 
O       6.20856332       6.20856332       3.22354366       0.00000000      -0.00000000       8.11183591 
H       6.20856332       6.97180232       2.62723466      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       5.44532432       2.62723466      -0.00000000      -5.21893682      -4.05591796 
O       6.20856332       6.20856332       6.32782532       0.00000000      -0.00000000       8.11183591 
H       6.20856332       6.97180232       5.73151632      -0.00000000       5.21893682      -4.05591796 
H       6.20856332       5.44532432       5.73151632      -0.00000000      -5.21893682      -4.05591796 
`

**Comment by felix5572** [comment]
@Feiyang472 bug fix in pr #97 , could you please take a try?
