### ISSUE TITLE
[Feature Request] Support [T F] flag in vasp/abacus

### ISSUE THREAD

**Issue by Angel-Jia** [deepmodeling/dpdata#742]
### Summary

Support [T F] flag in vasp/abacus

### Detailed Description

When converting between VASP and Abacus formats, the markers that indicate whether atoms are fixed (T/F) are lost, and the converted files assume all atoms are free to move. Is it possible to retain these markers during the conversion?

**Comment by wanghan-iapcm** [comment]
@pxlxingliang please consider the feature request for abacus. Thanks!

**Comment by pxlxingliang** [comment]
Ok, I will implement this feature.

**Comment by Angel-Jia** [comment]
Fixed with: #744
