### ISSUE TITLE
[Feature Request] pop method in LabeledSystem

### ISSUE THREAD

**Issue by anyangml** [deepmodeling/dpdata#747]
### Summary

To add a `pop` method to `LabeledSystem`. 

### Detailed Description

When we want to downsample or filter out certain frames from a system, it would be nice to modify the system in-place, so that we don't have to append to a new system. This will significantly save memory.

**Comment by njzjz** [comment]
I don't think it's possible as NumPy preallocates continuous memory for arrays.
